# Generated by Django 5.0.6 on 2024-06-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="score_achieved",
            field=models.DateField(null=True),
        ),
    ]
