# Generated by Django 5.0.6 on 2024-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0002_score_score_achieved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
