# Generated by Django 5.0.6 on 2024-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recall_it", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hard",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="normal",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
